name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Test basic functionality
        run: |
          python3 -c "import shelf; print('✓ Import works')"
          python3 shelf.py status || echo "✓ Status works"